# Generated by Django 4.1 on 2024-04-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
