# Generated by Django 4.1 on 2024-04-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_image_image_account_ima_created_ea74f6_idx"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
